artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/18Fo7s3UhABxtKbtT5jAjPGqlvUUR1pDW/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.keras
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.keras

prepare_dataset:
  root_dir: artifacts/data_preparation
  csv_file_path: artifacts/data_ingestion/styles.csv
  images_dir: artifacts/data_ingestion/images
  target_dir: artifacts/data_preparation/top10_classes
  label_col: articleType
  trainset_size: 0.8
  valset_size: 0.1
  testset_size: 0.1
  max_images: 1000


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras
  target_file_path: artifacts/data_ingestion/styles.csv
  csv_file_path: artifacts/data_ingestion/styles.csv
  images_dir: artifacts/data_ingestion/images
  target_dir: artifacts/training/top10_classes
  label_col: articleType